#color_bg = [0.0, 0.0, 0.0]

[[screens]]
host = "192.168.179.5"
#port = 5900
#password = ""
latitude  = -15.0
#longitude = 0.0
#lossy = true
use_pointer = false

[[screens]]
host = "192.168.179.4"
password = "hogehoge"
latitude  = -15.0
longitude = 180.0
