host = "192.168.179.5"
#port = 5900
#password = "hogehoge"
color_bg = [0.0, 0.0, 0.0]

[model]
path = "/sdcard/avocado.glb"
scaling = [0.25, 0.25, 0.25]
euler_zyx = [0.0, 0.0, 0.0]
translation = [0.0, 0.0, -1.0]
